sprint-1/step-2
AlekseiUsov/react-burger pull request #1
Opened 2023-01-19 14:07 UTC by AlekseiUsov

2023-01-19 14:38 UTC, andryxxa93 requested changes
Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Стили шрифтов в элементах хедера и модалки с ингредиентом не применяются из-за проблем с классами. <img width="1440" alt="Снимок экрана 2023-01-19 в 17 36 14" src="https://user-images.githubusercontent.com/60173362/213470438-3b340350-4a09-4f5c-8025-cabcc469dc1f.png">

- В консоли есть ошибки - их необходимо поправить

<img width="567" alt="Снимок экрана 2023-01-19 в 17 26 03" src="https://user-images.githubusercontent.com/60173362/213470389-8e3d09a6-5f05-44f6-a304-f4480d8b3a94.png">

- Добавьте проверку успешности запроса
- Вынесите логику из `App` в `BurgerConstructor`
- Избавьтесь от дубликатов типизации ингредиента

Более подробно описание проблемы смотрите комментарии в pull request.

Что понравилось:
- Сделали отписку от слушателя событий
- Хорошо декомпозировали компоненты
- Проект соответствует макету

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-01-19 14:38 UTC, andryxxa93 commented on src/App.jsx
> +        const resp = await fetch(`${api}/ingredients`);
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-01-19 14:38 UTC, andryxxa93 commented on src/App.jsx
> +    const getData = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-01-19 14:38 UTC, andryxxa93 commented on src/App.jsx
> +        <BurgerIngredients title={'Соберите бургер'} >
**Необходимо исправить**
Не стоит в `App` мапить список ингредиентов. Лучше передавайте его в `BurgerIngredients` и там уже рендерите списком.

2023-01-19 14:38 UTC, andryxxa93 commented on src/components/app-header-item/app-header-item.jsx
> +    <div className={`${props.isActive ? styles.active : styles.notActive} ${styles.block} p-4`}
**Необходимо исправить**
в шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в 3 спринте, не нужно сейчас это делать

2023-01-19 14:38 UTC, andryxxa93 commented on src/components/burger-constructor-item/burger-constructor.jsx
> +    _id: PropTypes.string.isRequired,
**Необходимо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-01-19 14:38 UTC, andryxxa93 commented on src/components/burger-ingredient-card/burger-ingredient-card.jsx
> +const BurgerIngredientCard = (props) => {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-01-19 14:38 UTC, andryxxa93 commented on src/components/modal-window/modal-window.jsx
> +            document.removeEventListener("keydown", handleEsc);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-01-19 14:38 UTC, andryxxa93 commented on tsconfig.json
> +{
**Можно лучше**
Пока что typescript не используется, поэтому конфиг не нужен

2023-01-19 14:38 UTC, andryxxa93 commented on src/App.test.tsx
> +import React from 'react';
**Можно лучше**
Этот файл не нужен, в будущем будет спринт посвященный тестам

2023-01-19 18:57 UTC, AlekseiUsov commented
> Проделана большая работа! Вы хорошо разобрались с функциональными компонентами, правильно используете useEffect и PropTypes.
> 
> Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.
> 
> Необходимо исправить:
> 
> * Стили шрифтов в элементах хедера и модалки с ингредиентом не применяются из-за проблем с классами. <img alt="Снимок экрана 2023-01-19 в 17 36 14" width="1440" src="https://user-images.githubusercontent.com/60173362/213470438-3b340350-4a09-4f5c-8025-cabcc469dc1f.png">
> * В консоли есть ошибки - их необходимо поправить
> 
> <img alt="Снимок экрана 2023-01-19 в 17 26 03" width="567" src="https://user-images.githubusercontent.com/60173362/213470389-8e3d09a6-5f05-44f6-a304-f4480d8b3a94.png">
> 
> * Добавьте проверку успешности запроса
> * Вынесите логику из `App` в `BurgerConstructor`
> * Избавьтесь от дубликатов типизации ингредиента
> 
> Более подробно описание проблемы смотрите комментарии в pull request.
> 
> Что понравилось:
> 
> * Сделали отписку от слушателя событий
> * Хорошо декомпозировали компоненты
> * Проект соответствует макету
> 
> В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.
> 
> Удачных правок!

Вечер добрый, Андрей. 
Спасибо за подробное разьяснение. 
Хотел уточнить у вас пару моментов.
1) Стили шрифтов в элементах хедера и модалки с ингредиентом не применяются из-за проблем с классами -
Классы в headere удалил (забыл просто убрать, делал стилизацию основываясь не на этот класс). Что касается переключение активных ссылок? На сколько критично их сейчас убрать?
В модалке с ингредиентами ничего не обнаружил.
2) В консоли есть ошибки - их необходимо поправить - по поводу ошибок. Не могу понять как их исправить.Понимаю что ошибка что происходит ожидание одного типа приходит другой. Не понимаю почему приходит title. Сделал скрин:
![image](https://user-images.githubusercontent.com/54838435/213534774-64490be2-804b-4173-9cd6-49847217f76a.png)
С остальным вроде все понятно, исправим в соответствие с вашими замечаниями)

2023-01-21 06:23 UTC, andryxxa93 commented
Часть ошибок точно связана с тем, что вы используете неверную конструкцию
Необходимо не так:
 ```
BurgerIngredientsGroup.propTypes = PropTypes.shape({
    className: PropTypes.string.isRequired,
    title: PropTypes.string.isRequired,
    children: PropTypes.arrayOf(cardTypes).isRequired
};
```

А вот так, без ` PropTypes.shape`:
```
BurgerIngredientsGroup.propTypes = {
    title: PropTypes.string.isRequired,
    children: PropTypes.arrayOf(cardTypes).isRequired
};
```

2023-01-21 06:24 UTC, andryxxa93 commented
Чтобы я смог проверить вашу работу вам необходимо залить изменения в ветку комитом и снова отправить работу на проверку.

2023-01-21 11:06 UTC, andryxxa93 approved these changes
Отлично! Все замечания учтены, вы отлично поработали. Ваша работа принята.
Желаю удачного продолжения обучения!

**Можно лучше**
Стили шрифтов в хедере и модальном окне по-прежнему берутся из системы, а не из стилей.

2023-02-20 17:41 UTC, merged