Sprint 3/step 1
AlekseiUsov/react-burger pull request #3
Opened 2023-02-20 17:33 UTC by AlekseiUsov

2023-02-20 18:13 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/RlhDlq46PsHMzQ>;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали).

- По чек-листу, Если пользователь отредактировал данные в форме, то появляются кнопки "Отмена" и "Сохранить". Т.е. изначально, вы должны скрывать кнопки. <https://disk.yandex.com/i/FfEhXBTNtRh8HA>.

### **Сделает код лучше:**

- <https://disk.yandex.com/i/T7zyeSAjxTq8Nw> - лучше сделать инпут пароль типа `password`.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-20 18:13 UTC, ArslanDev666 commented on src/components/protected-route-element/protected-route-element.jsx
> +};
**Можно лучше:**

Почему бы тут сразу не возвращать компонент Route, вместо element? Тогда бы нам не нужно было 2 раза указывать  `<Route path="/forgot-password" element={<UnProtectedRouteElement element={<ForgotPasswordPage />} />} />`, было бы просто:

```js
 <UnProtectedRouteElement path="/forgot-password" element={<ForgotPasswordPage />} />
```

Также, не забывайте про `propTypes`

2023-02-20 18:13 UTC, ArslanDev666 commented on src/pages/forgot-password-page/forgot-password-page.jsx
> +            <Button onClick={() => handleEmail(email)} htmlType="button" size="medium" extraClass="mt-6">Воccтановить</Button>
**Надо исправить:**

Обработчик отправки, должнен вешаться, на событие `onSubmit` в теге `form`.

2023-02-20 18:13 UTC, ArslanDev666 commented on src/pages/login-page/login-page.jsx
> +    const [password, setPassword] = useState('');
**Можно лучше**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-02-20 18:13 UTC, ArslanDev666 commented on src/pages/login-page/login-page.jsx
> +                <Button onClick={handleEmail} htmlType="button" size="medium" extraClass="mt-6">Войти</Button>
**Надо исправить:**

Обработчик отправки, должнен вешаться, на событие `onSubmit` в теге `form`.

2023-02-20 18:13 UTC, ArslanDev666 commented on src/pages/profile/profile-info/profile-info.jsx
> +                <Button onClick={() => updateInputsValue()} htmlType="button" size="medium">
**Надо исправить:**

Обработчик отправки, должнен вешаться, на событие `onSubmit` в теге `form`.

2023-02-20 18:13 UTC, ArslanDev666 commented on src/pages/profile/profile.jsx
> +                        onClick={() => logOut()}
**Можно лучше:**

Не совсем понимаю, зачем вы используйте здесь дополнительно аноним. функцию. Можно написать просто: `onClick={logOut}`, и всё будет работать))

2023-02-20 18:13 UTC, ArslanDev666 commented on src/pages/register-page/register-page.jsx
> +            <Button onClick={handleEmail} htmlType="button" size="medium" extraClass="mt-6">Войти</Button>
**Надо исправить:**

Обработчик отправки, должнен вешаться, на событие `onSubmit` в теге `form`.

2023-02-20 18:13 UTC, ArslanDev666 commented on src/pages/reset-password-page/reset-password-page.jsx
> +            <Button onClick={handleEmail} htmlType="button" size="medium" extraClass="mt-6">Сохранить</Button>
**Надо исправить:**

Обработчик отправки, должнен вешаться, на событие `onSubmit` в теге `form`.

2023-02-20 18:13 UTC, ArslanDev666 commented on src/services/actions/routers/get-profile-data.jsx
> +        })
**Можно лучше:**

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      setCookie("accessToken", refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-02-21 11:41 UTC, AlekseiUsov commented
День добрый.
Все критические замечания исправил, остальными займусь чуть позже, т.к. не хватает времени, уже подгонятет куратор.

2023-02-21 17:50 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Сделает код лучше:**

- В приложении не должно быть консоль логов или дебаггеров.

2023-03-02 12:54 UTC, merged